CREATE TABLE PERSON
(
    PKEY INTEGER PRIMARY KEY,
    NAME INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX__PERSON__NAME ON PERSON (NAME);

CREATE TABLE DRUG
(
    PKEY INTEGER PRIMARY KEY,
    NAME INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX__DRUG__NAME ON DRUG (NAME);

CREATE TABLE MEDICATION
(
    PKEY        INTEGER PRIMARY KEY,
    PERSON_PKEY INTEGER NOT NULL,
    DRUG_PKEY   INTEGER NOT NULL,
    DATE        INTEGER NOT NULL,
    FOREIGN KEY (PERSON_PKEY) REFERENCES PERSON (PKEY),
    FOREIGN KEY (DRUG_PKEY) REFERENCES DRUG (PKEY)
);

PRAGMA
user_version = 1;