CREATE TABLE DRUG_COMPOSITION
(
    PKEY INTEGER PRIMARY KEY,
    NAME INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX__DRUG_COMPOSITION__NAME ON DRUG_COMPOSITION (NAME);

CREATE TABLE DRUG_DOSAGE
(
    PKEY                  INTEGER PRIMARY KEY,
    DRUG_PKEY             INTEGER NOT NULL,
    DRUG_COMPOSITION_PKEY INTEGER NOT NULL,
    QUANTITY              INTEGER NOT NULL,
    FOREIGN KEY (DRUG_PKEY) REFERENCES DRUG (PKEY),
    FOREIGN KEY (DRUG_COMPOSITION_PKEY) REFERENCES DRUG_COMPOSITION (PKEY)
);

CREATE UNIQUE INDEX IDX__DRUG_DOSAGE__DRUG_PKEY__DRUG_COMPOSITION_PKEY ON DRUG_DOSAGE (DRUG_PKEY, DRUG_COMPOSITION_PKEY);

INSERT INTO DRUG_COMPOSITION (PKEY, NAME)
VALUES (1, 'Paracétamol');

INSERT INTO DRUG_DOSAGE (PKEY, DRUG_PKEY, DRUG_COMPOSITION_PKEY, QUANTITY)
VALUES (1, 1, 1, 1000);

INSERT INTO DRUG_DOSAGE (PKEY, DRUG_PKEY, DRUG_COMPOSITION_PKEY, QUANTITY)
VALUES (2, 2, 1, 500);

INSERT INTO DRUG_DOSAGE (PKEY, DRUG_PKEY, DRUG_COMPOSITION_PKEY, QUANTITY)
VALUES (3, 3, 1, 1000);

PRAGMA
    user_version = 4;