INSERT INTO DRUG (PKEY, NAME)
VALUES (4, 'Humex Jour');

INSERT INTO DRUG (PKEY, NAME)
VALUES (5, 'Humex Nuit');

INSERT INTO DRUG_DOSAGE (PKEY, DRUG_PKEY, DRUG_COMPOSITION_PKEY, QUANTITY)
VALUES (4, 4, 1, 500),
       (5, 5, 1, 500);

PRAGMA
    user_version = 7;