ALTER TABLE PERSON
    ADD COLUMN ADULT INTEGER NOT NULL DEFAULT 1;

UPDATE PERSON
SET ADULT = 0
WHERE PKEY IN (3); -- Clémentine

ALTER TABLE DRUG
    ADD COLUMN FOR_ADULT INTEGER NOT NULL DEFAULT 1;
ALTER TABLE DRUG
    ADD COLUMN FOR_CHILD INTEGER NOT NULL DEFAULT 1;

UPDATE DRUG
SET FOR_CHILD = 0
WHERE PKEY IN (2, 3, 4, 5); -- Humex, CoDoliprane (2cp), Humex jour, Humex nuit

PRAGMA
    user_version = 8;