INSERT INTO DRUG (PKEY, NAME, FOR_ADULT, FOR_CHILD)
VALUES (9, 'Smecta', 1, 1);

INSERT INTO DRUG_COMPOSITION (PKEY, NAME)
VALUES (2, 'Diosmectite');

INSERT INTO DRUG_DOSAGE (PKEY, DRUG_PKEY, DRUG_COMPOSITION_PKEY, QUANTITY)
VALUES (6, 7, 2, 3000);

INSERT INTO DRUG_DOSAGE (PKEY, DRUG_PKEY, DRUG_COMPOSITION_PKEY, QUANTITY)
VALUES (7, 9, 2, 3000);

PRAGMA
    user_version = 12;