INSERT INTO DRUG (PKEY, NAME, FOR_ADULT, FOR_CHILD)
VALUES (11, 'Topalgic', 0, 1);

INSERT INTO DRUG_COMPOSITION (PKEY, NAME)
VALUES (3, 'Tramadol');

INSERT INTO DRUG_DOSAGE (PKEY, DRUG_PKEY, DRUG_COMPOSITION_PKEY, QUANTITY)
VALUES (8, 11, 3, 0);

PRAGMA
    user_version = 14;