INSERT INTO DRUG (PKEY, NAME, FOR_ADULT, FOR_CHILD)
VALUES (12, 'Immodium Caps', 1, 0);

INSERT INTO DRUG_COMPOSITION (PKEY, NAME)
VALUES (4, 'Loperamide');

INSERT INTO DRUG_DOSAGE (PKEY, DRUG_PKEY, DRUG_COMPOSITION_PKEY, QUANTITY)
VALUES (9, 12, 4, 4);

PRAGMA
    user_version = 15;