name: Build and Tests (push on main)

on:
  push:
    branches: ["main"]

env:
  DOTNET_VERSION: "6.0"
  PROJECT_NAME: "WebApplication1"

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Npm Install
        run: |
          if [ -e package.json ]; then
            npm install
          fi
        working-directory: src/${{ env.PROJECT_NAME }}
      - name: Transpile and bundle Typescript
        run: |
          if [ -e package.json ]; then
            npm run bundle
          fi
        working-directory: src/${{ env.PROJECT_NAME }}
